# Generated by Django 5.1.4 on 2025-12-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='learnings',
            field=models.TextField(blank=True, help_text='What did you learn from this project?'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default=1, help_text='Comma separated, e.g. Django, Bootstrap, SQLite', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
