# Generated by Django 5.1.4 on 2025-12-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_learnings_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='learnings',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
    ]
