# Generated by Django 5.1.4 on 2025-12-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_project_learnings_remove_project_tech_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, help_text='Link to deployed site', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_link',
            field=models.URLField(blank=True, help_text='Link to GitHub', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default=1, help_text='Comma separated technologies', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
