# Generated by Django 5.1.4 on 2025-12-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill_testimonial_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_video',
            field=models.FileField(blank=True, help_text='Upload a short .mp4 video or .gif showing the project in action.', null=True, upload_to='portfolio/videos/'),
        ),
    ]
