# Generated by Django 5.1.4 on 2025-12-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_demo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date_earned',
            field=models.DateField(blank=True, help_text='When did you get this?', null=True),
        ),
    ]
