# Generated by Django 4.2.27 on 2025-12-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_certificate_date_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_earned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
