# Generated by Django 4.2.27 on 2025-12-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_certificate_date_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_video',
            field=models.URLField(blank=True, help_text='Paste Cloudinary / YouTube / Drive video URL', null=True),
        ),
    ]
