# Generated by Django 4.2.27 on 2025-12-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_project_demo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
