# Generated by Django 4.2.27 on 2025-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_project_demo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_video',
            field=models.FileField(blank=True, help_text='Upload a short .mp4 video or .gif showing the project in action.', null=True, upload_to='portfolio/videos/'),
        ),
    ]
