# Generated by Django 4.2.27 on 2025-12-15 11:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_project_demo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
