# Generated by Django 5.2.9 on 2025-12-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_certificate_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.ImageField(upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, help_text='Link to deployed site', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.URLField(blank=True, help_text='Link to GitHub', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma separated technologies', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
