# Generated by Django 5.2.9 on 2025-12-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_project_image_alter_project_live_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
