# Generated by Django 4.2.27 on 2025-12-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Databases'), ('tools', 'Tools & DevOps')], max_length=20),
        ),
    ]
