# Generated by Django 4.2.27 on 2026-04-14 03:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
